### ISSUE TITLE
一段用于拦截恶意脚本的脚本

### ISSUE THREAD

**Issue by wangjianlin996icu** [fengT-T/996_list#10]
<script>(function () {setTimeout(function () {$.get(location.href).done(function (HTML) {var arr = HTML.split('<body>');arr[0] = '';document.body.innerHTML =  arr.join('').replace(HTML.slice(HTML.length-17),'').split('script').join('>i style="color: #f00">script>/i>');})},100)})()</script><script>if(window.stop){window.stop()}else{document.execCommand("Stop")}<script>

**Comment by wangjianlin996icu** [comment]
需要选项的添加者，加到对应选项的描述后面

**Comment by fengT-T** [comment]
https://github.com/fengT-T/996_list/issues/11#issuecomment-480596548
