### ISSUE TITLE
有xss攻击

### ISSUE THREAD

**Issue by zxc948406613** [fengT-T/996_list#11]
可以看一下备份中点击苏宁的时候，会出现xss注入的提示

**Comment by fengT-T** [comment]
i know 我只是跳转过去而且，新站我在筹划中，

**Comment by fengT-T** [comment]
具体描述可以看戏精附体的我的表演 #2

**Comment by fengT-T** [comment]
全新版本正在开发  https://fengt-t.github.io/996_list/#/
