### ISSUE TITLE
老哥，先把xss修好吧。

### ISSUE THREAD

**Issue by leo66123** [fengT-T/996_list#2]

**Comment by fengT-T** [comment]
这里面可能有些误会，https://feathub.com/LinXueyuanStdio 这个网站实际上不是我写的，我只是负责跳转过去，因为这个网站问题实在太大，一开始的是连中文搜索都没有，有卡的不行
后面有发生xss之类的问题，我只能说，这网站看个列表就行了，投个票就行了，评论里面已经是xss满天飞了

**Comment by fengT-T** [comment]
我做这个的原因就是为了能够去显示出全部的列表，实际上显示个列表都很卡了

**Comment by fengT-T** [comment]
而且讲句良心话，要是能做出xss，那差不多是我的光辉职业生涯的最大污点了

**Comment by fengT-T** [comment]
![@HO~{Q247~_AEY41C G8ONE](https://user-images.githubusercontent.com/20101525/55274400-d20b8d80-5312-11e9-831e-36c00755cba2.jpg)

**Comment by fengT-T** [comment]
我是不是言语过激了一些啊

**Comment by zhengzhou** [comment]
你只是戏多了点 😂😂

**Comment by fengT-T** [comment]
https://github.com/fengT-T/996_list/issues/11#issuecomment-480596548
