### ISSUE TITLE
能把投票接口也弄过来么

### ISSUE THREAD

**Issue by Alan110** [fengT-T/996_list#3]
添加投票功能

**Comment by fengT-T** [comment]
我也想啊，而且看那个网站已经很不爽了，关键是，接口是他弄的，跨域有问题，更本弄不过来，而且还要拿session之类的，还不如自己写一个了

**Comment by fengT-T** [comment]
https://github.com/996icu/996.ICU/blob/master/blacklist/blacklist.md
