### ISSUE TITLE
希望能跟这个repo的开发者聊聊

### ISSUE THREAD

**Issue by XinyuJing** [fengT-T/996_list#44]
Hi 996_list的开发者，

我是《人物》杂志的记者（因为这是个公开的地方，就先不透露名字啦），我正在写一篇围绕着996.icu展开的抗议故事和其中的个体，目前已经和955.WLB、996.law/action、996.OD、996.Leave和anti-996 license的发起者聊过了，很希望能跟每一个996.XX的发起者聊一聊你们的故事。如果你愿意，可否写邮件给我？jxy940806@163.com。请放心我会竭尽全力保护好你的隐私。

XY

**Comment by boycott996** [comment]
> 非常感谢你的来信！先自我介绍下吧，我是《人物》杂志的记者荆欣雨，你可以叫我小雨。我在写一篇围绕996.icu展开来的抗议故事和其中的愿意发声的个体。这两周以来，我已经跟996.law/action,996.OD,996.leave，955.WLB和anti-996 license的发起者都通过见面或语音的方式聊过了，今天早上也联系上了996.avenger和996.petition的发起者。我也非常希望和你聊聊你参与996.icu的故事，和你本人996的经历（如果有的话），你对于这一议题的看法等等。

> 我猜你会觉得微信并不安全。我之前与两位程序员用了whirlmeet.com这个网站语音，其中一位check过它的代码，说是安全的。不知道你意下如何？如果可以的话，这周我在上海出差见一些人，我们或许可以周六日约个时间？当然，如果你在京沪两地，愿意与我见面，那最好不过，但我永远理解这个选题里所有程序员的谨慎和对自己的保护，请相信我也会竭尽全力保护好你的隐私

请大家务必注意,这是国宝

**Comment by gnoloehz** [comment]
@boycott996 我是996.OD的作者，你这里贴出别人的信息是违法的，请删除你的信息
