### ISSUE TITLE
发现一个自称是人物杂志记者的疑似钓鱼人员

### ISSUE THREAD

**Issue by boycott996** [fengT-T/996_list#45]
> 非常感谢你的来信！先自我介绍下吧，我是《人物》杂志的记者xxx，你可以叫我小x。我在写一篇围绕996.icu展开来的抗议故事和其中的愿意发声的个体。这两周以来，我已经跟996.law/action,996.OD,996.leave，955.WLB和anti-996 license的发起者都通过见面或语音的方式聊过了，今天早上也联系上了996.avenger和996.petition的发起者。我也非常希望和你聊聊你参与996.icu的故事，和你本人996的经历（如果有的话），你对于这一议题的看法等等。

> 我猜你会觉得微信并不安全。我之前与两位程序员用了whirlmeet.com这个网站语音，其中一位check过它的代码，说是安全的。不知道你意下如何？如果可以的话，这周我在上海出差见一些人，我们或许可以周六日约个时间？当然，如果你在京沪两地，愿意与我见面，那最好不过，但我永远理解这个选题里所有程序员的谨慎和对自己的保护，请相信我也会竭尽全力保护好你的隐私。

大家有没有收到这个人的信息,个人建议保持警惕

**Comment by fengT-T** [comment]
我哪有时间去给采访啊，而且微信确实也不安全，毕竟有手机号，实际上如果想聊的话随便找个gmail邮件联系就好了

**Comment by boycott996** [comment]
确认是钓鱼,他说已经采访你了

**Comment by fengT-T** [comment]
我一般只和陌生人邮件联系

**Comment by CPdogson** [comment]
whirlmeet.com是我提供的，是一个第三方jitsi服务器，至少我能确定它是安全的，我也接受过这位记者的采访。
jitsi是一个在GitHub上开源的点对点加密会议工具。
