### ISSUE TITLE
我怎么打不开这个列表了，数据加载失败

### ISSUE THREAD

**Issue by zzxcvbnm19** [fengT-T/996_list#7]

**Comment by fengT-T** [comment]
大不开就对了，那个网站已经卡到一个境界了

**Comment by fengT-T** [comment]
那个网站已经卡到爆炸了吧

**Comment by fengT-T** [comment]
https://feathub.com/LinXueyuanStdio/996.ICU

**Comment by zzxcvbnm19** [comment]
网页都出来了，json数据全挂了

**Comment by fengT-T** [comment]
我的网站是用的gitpage没，但是投票的网站和我的王扎你不是一个网站啊，我是取的他的数据

**Comment by zzxcvbnm19** [comment]
就是说现在投票的网站挂了啊？

**Comment by fengT-T** [comment]
这个网站的人已经撒手不管了，当时谁找的这个破站，日了狗了。

**Comment by zzxcvbnm19** [comment]
投票记录应该还没有备份吧？是不是之前的投票都没了。。。。

**Comment by fengT-T** [comment]
这个倒是不会吧

**Comment by fengT-T** [comment]
我感觉有可能没有备份

**Comment by zzxcvbnm19** [comment]
不会是这两天访问量激增，服务器挂了或者欠费了吧

**Comment by fengT-T** [comment]
欠费倒是不至于

**Comment by fengT-T** [comment]
感觉挂了的可能性巨大

**Comment by zzxcvbnm19** [comment]
嗯 刚看了访问量排名，最近一周这个网站从35W以上的排名直接涨到1W名以内了。。。

**Comment by fengT-T** [comment]
但是周末虽然卡了些但是还是有返回数据的，然后今天就凉了，早知道早点备份数据了。

**Comment by zhangxy95** [comment]
啊 还想说这个列表一直转呢

**Comment by LanceVan** [comment]
https://web.archive.org/web/20190330073509/https://feathub.com/formulahendry/955.WLB

这个上面竟然还有备份 太感人了

我赶紧保存了一份

**Comment by withnino** [comment]
> https://web.archive.org/web/20190330073509/https://feathub.com/formulahendry/955.WLB
> 
> 这个上面竟然还有备份 太感人了
> 
> 我赶紧保存了一份

这个只打得开第一页吗？

**Comment by zzxcvbnm19** [comment]
> https://web.archive.org/web/20190330073509/https://feathub.com/formulahendry/955.WLB
> 
> 这个上面竟然还有备份 太感人了
> 
> 我赶紧保存了一份

我怎么还是打不开？需要翻墙吗

**Comment by zzxcvbnm19** [comment]
要翻墙啊。  有996的数据吗

**Comment by 7oranger** [comment]
上面的备份是955的，而且只能看到第一页。。

**Comment by fengT-T** [comment]
既然有备份，那么重建这个网站就更义不容辞了

**Comment by fengT-T** [comment]
@LanceVan 但是996 的数据打不开了，只能看第一页，数据就这么毁了

**Comment by fengT-T** [comment]
可能要重新收集数据了

**Comment by withnino** [comment]
> 可能要重新收集数据了

有996的截图

**Comment by fengT-T** [comment]
截图何在 @withnino

**Comment by fengT-T** [comment]
能打开了飞速备份数据

**Comment by zzxcvbnm19** [comment]
能不能弄个分页啊，好几百条数据了

**Comment by fengT-T** [comment]
会的

**Comment by withnino** [comment]
> 会的

https://github.com/withnino/996_list/blob/master/2019-03-31_114729.png
这是996的截图，刚刚点错了提交到你那了

**Comment by fengT-T** [comment]
@withnino 原来那个网站突然能访问了，然后现在我已经使用备份了，速度快很多。你来试试

**Comment by withnino** [comment]
@fengT-T 谢谢，已经备份

**Comment by fengT-T** [comment]
https://github.com/fengT-T/996_list/issues/11#issuecomment-480596548
